name = "MKLParido64"
uuid = "3956db9c-e912-4589-8200-7206deca4b74"
authors = ["Benoit Pasquier <briochemc@gmail.com>"]
version = "0.1.0"

[deps]
MKL = "33e6dc65-8f57-5167-99aa-e5a354878fb2"
Pardiso = "46dd5b70-b6fb-5a00-ae2d-e8fea33afaf2"

[compat]
MKL = "0.9.0"
Pardiso = "1.0.0"
